name: Android APK Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode release keystore
        run: |
          echo "${{ secrets.PENNY_RELEASE_KEY_BASE64 }}" | base64 --decode > android/app/penny-release-key.jks
      - name: Generate key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=penny-release-key.jks" >> android/key.properties

      - name: Build Android APK
        run: flutter build apk --release
        # If you want to build APKs for different architectures, uncomment the line below
      - run: flutter build apk --release --split-per-abi

      - name: List files in APK output directory
        run: ls -R build/app/outputs/flutter-apk/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: App Release ${{ github.ref_name }}
          body: |
            A new release of the app is available.
            
            This release includes:
            - **Bug fixes** ğŸ›
            - **New features** âœ¨
          files: build/app/outputs/flutter-apk/*.apk